class_name CeviriEn
extends RefCounted
## Ingilizce tablo (anahtar = Turkce kaynak metin). Bkz. ceviri.gd.
## Metinler dogal ve kisa; videolar X ve YouTube'da Ingilizce yayinlaniyor.
## Bicim belirteclerinin (%d, %s, %.1f) sayisi ve sirasi kaynakla ayni olmali.
const EN := {
	# --- menu ---
	"Derin Kazı": "Deep Dig",
	"Kaz, sat, geliştir. 250 metre aşağıda çekirdek var.": "Dig, sell, upgrade. The core is 250 meters down.",
	"01 / YÜZEY": "01 / SURFACE",
	"Oyna": "Play",
	"Günlük dünya": "Daily world",
	"Derin Mod": "Deep Mode",
	"Yeni dünya": "New world",
	"Tohum kodu": "Seed code",
	"Ayarlar": "Settings",
	"Çıkış": "Quit",
	"Emin misin? Tekrar dokun": "Sure? Tap again",
	"A/D yürü  ·  S aşağı kaz  ·  W/Boşluk yüksel  ·  E üs": "A/D move  ·  S dig down  ·  W/Space fly  ·  E base",
	"Alt köşelere dokun: yürü  ·  ortaya: kaz  ·  ▲: yüksel": "Tap bottom corners: move  ·  middle: dig  ·  ▲: fly",
	"▼ DERİN MOD x1 ▼": "▼ DEEP MODE x1 ▼",
	"DERİN MOD x%d": "DEEP MODE x%d",
	"7. eser bulundu": "Artifact 7 found",
	"7. eser yalnız burada": "Artifact 7 only here",
	"Derin Mod x%d — devam et (%d m, %d ₺)": "Deep Mode x%d — continue (%d m, %d ₺)",
	"Derin Mod x%d — yeni tohum, eserler kalır": "Deep Mode x%d — new seed, artifacts stay",
	"GÜNLÜK %s": "DAILY %s",
	"  ·  BUGÜN EN DERİN %d m": "  ·  TODAY'S DEEPEST %d m",
	"KAYIT YOK · YENİ DÜNYA ÜRETİLECEK": "NO SAVE · A NEW WORLD WILL BE MADE",
	"TOHUM %s  ·  %d ₺  ·  EN DERİN %d m  ·  ESER %d/%d%s": "SEED %s  ·  %d ₺  ·  DEEPEST %d m  ·  ARTIFACTS %d/%d%s",
	"%d KARO KAZILMIŞ": "%d TILES DUG",
	"7 harf — ör. BCDFGHJ": "7 letters — e.g. BCDFGHJ",
	"Bu tohumla yeni dünya": "New world with this seed",
	"Şu anki dünyanın kodu: %s\n\nKodu bir arkadaşına ver, aynı dünyayı oynasın. Kod 7 harf; I, O, 0 ve 1 yok (karışmasın diye).\n\nBaşkasının kodunu girip yeni dünya açabilirsin — ana ilerlemen sıfırlanır.": "Your current world's code: %s\n\nGive the code to a friend and they play the same world. Codes are 7 letters; no I, O, 0 or 1 (to avoid mix-ups).\n\nYou can enter someone else's code to start a new world — your main progress resets.",
	"— (henüz dünya yok)": "— (no world yet)",
	"Kod geçerli.": "Code is valid.",
	"Kod geçersiz — harfleri kontrol et.": "Invalid code — check the letters.",
	"Kod geçersiz — 7 harf olmalı ve sağlaması tutmalı.": "Invalid code — it must be 7 letters and pass the check.",
	"Kapat  (Esc)": "Close  (Esc)",
	# --- ayarlar ---
	"Müzik": "Music",
	"Efekt": "Effects",
	"Ekran sarsıntısı": "Screen shake",
	"Tam ekran": "Fullscreen",
	"Dil": "Language",
	"Kapat": "Close",
	"Cihazını yatay çevir": "Rotate your device to landscape",
	# --- oyun ici HUD ---
	"YAKIT %d/%d": "FUEL %d/%d",
	"YÜK %d/%d": "LOAD %d/%d",
	"CAN %d/%d": "HP %d/%d",
	"YAKIT 0/0": "FUEL 0/0",
	"YÜK 0/0": "LOAD 0/0",
	"CAN 0": "HP 0",
	"ÇEKİRDEK %d m": "CORE %d m",
	"ZİNCİR x%d  ×%.2f": "CHAIN x%d  ×%.2f",
	"DİNAMİT %d": "DYNAMITE %d",
	"DİNAMİT 0": "DYNAMITE 0",
	"RADAR yok": "RADAR none",
	"RADAR KAPA": "RADAR OFF",
	"RADAR AÇ": "RADAR ON",
	"İŞARET %d m": "MARKER %d m",
	"İŞARET KOY": "SET MARKER",
	"GÜNLÜK": "DAILY",
	"Radar: yakında maden yok": "Radar: no ore nearby",
	"Radar %s %s %d m": "Radar %s %s %d m",
	"Üs": "Base",
	"Harita": "Map",
	"▼ KAZ": "▼ DIG",
	"▲ UÇ": "▲ FLY",
	# --- ipuclari ---
	"Üs düğmesi": "Base button",
	"Harita düğmesi": "Map button",
	"DİNAMİT düğmesi": "DYNAMITE button",
	"RADAR düğmesi": "RADAR button",
	"İŞARET düğmesi": "MARKER button",
	"%s — buraya dönüş işareti koy; üsten tek seferlik ışınlanırsın.": "%s — drop a return marker here; teleport back once from the base.",
	"R — buraya dönüş işareti koy; üsten T ile tek seferlik ışınlanırsın.": "R — drop a return marker here; teleport back once with T from the base.",
	"İşaret %d m'de. Üsten %s ile tek seferlik ışınlan.": "Marker at %d m. Teleport there once via %s from the base.",
	"İşaret %d m'de. Üsten T ile tek seferlik ışınlan.": "Marker at %d m. Teleport there once with T from the base.",
	"Q — en yakın madeni HUD'da gösterir": "Q — shows the nearest ore on the HUD",
	"%s — en yakın madeni HUD'da gösterir": "%s — shows the nearest ore on the HUD",
	"Lav ve sıcak katmanlarda hasar almazsın": "No damage from lava and hot layers",
	"F ile 3x3 patlat": "Press F to blast 3x3",
	"%s ile 3x3 patlat": "Use %s to blast 3x3",
	"T ile kur, anında yolculuk": "Place with T, instant travel",
	"%s ile kur, anında yolculuk": "Place with %s, instant travel",
	"DEPREM  %0.1f sn": "QUAKE  %0.1f s",
	"Güvendesin — yüzeye yakın kal.": "You're safe — stay near the surface.",
	"%s ile YÜZEYE ÇIK": "%s to SURFACE",
	"W ile YÜZEYE ÇIK": "W to SURFACE",
	"%s   →   +%d ₺ ikramiye": "%s   →   +%d ₺ bonus",
	"DERİNDE KAL   →   %d hasar": "STAY DEEP   →   %d damage",
	"KAÇIŞ! Yakıt bitmeden yüzeye çık.": "ESCAPE! Reach the surface before fuel runs out.",
	"%s — sat, geliştir, yakıt   •   %s — mini harita": "%s — sell, upgrade, fuel   •   %s — mini map",
	"E — Üs (sat, geliştir, yakıt)   •   T — ışınlanma   •   M — harita": "E — Base (sell, upgrade, fuel)   •   T — teleport   •   M — map",
	"Yük dolu! Satmak için üsse dön.": "Load full! Return to base to sell.",
	"Can azaldı — üsse dön, onarım bedava.": "Low HP — return to base, repairs are free.",
	"Yakıt azalıyor — %s ile ışınlanma panelini aç.": "Fuel running low — open the teleport panel with %s.",
	"Yakıt azalıyor — üsse dön (T ile ışınlanabilirsin).": "Fuel running low — head back (T teleports you).",
	"%s alanına basılı tut. İlk bakır damarı hemen altında.": "Hold the %s area. The first copper vein is right below.",
	"S / ↓ ile aşağı kaz. İlk bakır damarı hemen altında.": "Hold S / ↓ to dig down. The first copper vein is right below.",
	"Madeni sat: %s ile yüzeye çık, sonra %s.": "Sell ore: fly up with %s, then use %s.",
	"Madeni sat: W ile yüzeye çık, üste E'ye bas.": "Sell ore: fly up with W, then press E at the base.",
	"Dinamit yok — üsten al.": "No dynamite — buy some at the base.",
	"Dinamit için zemine bas.": "Stand on the ground to place dynamite.",
	"Maden radarı yok — üsten al.": "No ore radar — buy it at the base.",
	"İşaret üste konmaz — yeraltında koy.": "Markers can't go on the surface — place it underground.",
	"Yük dolu, maden alınmadı!": "Load full, ore not picked up!",
	"Kazı zinciri! Aynı madeni sürdür.": "Dig chain! Keep going with the same ore.",
	"Bu kaya için Matkap Sv%d gerekli.": "This rock needs Drill Lv%d.",
	"+%d dinamit": "+%d dynamite",
	"+%d yakıt": "+%d fuel",
	"Sandık: %s": "Chest: %s",
	"+%d parça": "+%d pieces",
	"Düşürdüğün yükü geri aldın (%d parça).": "You recovered your dropped load (%d pieces).",
	# --- uyarilar / oyun sonu ---
	"ESER BULUNDU  (%d/%d)\n\n%s — %s\n\n%s\n\nMüzeye eklendi (üs menüsünden okuyabilirsin).": "ARTIFACT FOUND  (%d/%d)\n\n%s — %s\n\n%s\n\nAdded to the museum (read it from the base menu).",
	"ÇEKİRDEĞE DOKUNDUN!\n\nKabuk çöküyor — yüzeye kaç!\nDepo dolduruldu, tüm aletler açık.\nSüre yakıtın kadar.": "YOU TOUCHED THE CORE!\n\nThe crust is collapsing — run for the surface!\nTank refilled, all tools unlocked.\nYou have as long as your fuel lasts.",
	"Yüzeye çekildin.": "You were pulled to the surface.",
	"Kaçış başarısız — yüzeye çekildin.": "Escape failed — you were pulled to the surface.",
	"Çekme ücreti: %d ₺": "Tow fee: %d ₺",
	"Yükün yarısı %d m'de sandıkta kaldı — geri alabilirsin.": "Half your load stayed in a crate at %d m — you can get it back.",
	"Yakıt doldurmak için üs menüsünü aç.": "Open the base menu to refuel.",
	"Tamam": "OK",
	"Bütün eserleri topladın — çekirdeğin hikâyesi müzede tamam.": "You found every artifact — the core's story is complete in the museum.",
	"Eksik eserler çekirdeğin hikâyesinin kalan parçalarını taşıyor.": "The missing artifacts carry the rest of the core's story.",
	"Menüde DERİN MOD açıldı: yeni tohum, sert kaya, dar ışık, sık deprem ve yalnız orada bulunan 7. eser — eser bonusların kalır.": "DEEP MODE is now open in the menu: new seed, harder rock, narrow light, frequent quakes and a 7th artifact found only there — your artifact bonuses stay.",
	"Derin Mod x%d tamamlandı. Menüde x%d açıldı — eserlerin seninle gelir.": "Deep Mode x%d complete. x%d is open in the menu — your artifacts come with you.",
	"ÇEKİRDEK ÇIKARILDI!": "CORE EXTRACTED!",
	"Tekrar": "Again",
	"Tekrar — Derin Mod x%d": "Again — Deep Mode x%d",
	"Menüye dön": "Back to menu",
	"Menüye dön (kaydeder)": "Back to menu (saves)",
	"SÜRE %s  ·  EN DERİN %d m  ·  PARA %d ₺  ·  ESER %d/%d  ·  TOHUM %s": "TIME %s  ·  DEEPEST %d m  ·  MONEY %d ₺  ·  ARTIFACTS %d/%d  ·  SEED %s",
	"Bu dünya:  %d karo kazıldı  ·  %d deprem  ·  %d yüzeye çekilme  ·  %d ₺ satış": "This world:  %d tiles dug  ·  %d quakes  ·  %d tows  ·  %d ₺ sold",
	"Toplam (bütün dünyalar):  %d karo  ·  %d deprem  ·  %d çekilme  ·  %d ₺ satış  ·  %s oyun": "Total (all worlds):  %d tiles  ·  %d quakes  ·  %d tows  ·  %d ₺ sold  ·  %s played",
	"  Kabuk nöbeti ikramiyesi +%d ₺.": "  Crust-watch bonus +%d ₺.",
	"  Derinde kaldın: -%d can.": "  You stayed deep: -%d HP.",
	"DEPREM! %d karo tünel kapandı, %d yeni damar/gaz çıktı.%s": "QUAKE! %d tunnel tiles closed, %d new veins/gas pockets appeared.%s",
	# --- duraklat / paneller ---
	"Duraklatıldı": "Paused",
	"Devam et": "Resume",
	"A/D veya ←/→ yürü ve yana kaz  ·  S veya ↓ aşağı kaz  ·  W/Boşluk pervane\nE üs  ·  T ışınlanma  ·  R dönüş işareti  ·  Q radar  ·  F dinamit  ·  M harita  ·  Esc duraklat\nGamepad: sol çubuk, A pervane, X üs, LB radar, RB ışınlanma, B işaret, Y dinamit, Start duraklat": "A/D or ←/→ walk and dig sideways  ·  S or ↓ dig down  ·  W/Space fly\nE base  ·  T teleport  ·  R return marker  ·  Q radar  ·  F dynamite  ·  M map  ·  Esc pause\nGamepad: left stick, A fly, X base, LB radar, RB teleport, B marker, Y dynamite, Start pause",
	"Alt sol / alt sağ köşe: o yöne yürü ve yana kaz  ·  Alt orta: aşağı kaz  ·  ▲ alanı: pervaneyle yüksel\nSağ üst: Üs · Harita · ■ duraklat  ·  Sol: DİNAMİT · RADAR · İŞARET": "Bottom-left / bottom-right corner: walk and dig sideways  ·  Bottom middle: dig down  ·  ▲ area: fly up\nTop right: Base · Map · ■ pause  ·  Left: DYNAMITE · RADAR · MARKER",
	"ÜS": "BASE",
	"MÜZE": "MUSEUM",
	"IŞINLANMA": "TELEPORT",
	"Yük: %d/%d ağırlık (%d parça)": "Load: %d/%d weight (%d pieces)",
	"   %s x%d = %d ₺  (%d ağırlık)": "   %s x%d = %d ₺  (%d weight)",
	"   zincir ikramiyesi +%d ₺": "   chain bonus +%d ₺",
	"Para: %d ₺   •   Dinamit: %d   •   İstasyon kiti: %d": "Money: %d ₺   •   Dynamite: %d   •   Station kit: %d",
	"Sat  (+%d ₺)": "Sell  (+%d ₺)",
	"Yakıt doldur  (%d ₺)": "Refuel  (%d ₺)",
	"%s Sv%d — en üst": "%s Lv%d — max",
	"%s Sv%d→Sv%d  (%d ₺)": "%s Lv%d→Lv%d  (%d ₺)",
	"%s ✔ — %s": "%s ✔ — %s",
	"Dinamit x1  (%d ₺) — %s": "Dynamite x1  (%d ₺) — %s",
	"İstasyon kiti  (%d ₺) — %s": "Station kit  (%d ₺) — %s",
	"Müze  (%d/%d eser)": "Museum  (%d/%d artifacts)",
	"Geri": "Back",
	"Her eser hem kalıcı bir bonus verir hem de çekirdeğin\nsırrından bir parça anlatır — %d/%d parça toplandı.": "Each artifact grants a permanent bonus and tells a piece of\nthe core's secret — %d/%d pieces found.",
	"Bağlısın.": "You're connected.",
	"Yolculuk için üste ya da bir istasyona gel.": "Come to the base or a station to travel.",
	"Yüzeye dön (üs)": "Return to surface (base)",
	"İstasyon — %d m": "Station — %d m",
	"İşarete ışınlan — %d m  (tek kullanımlık, sonra silinir)": "Teleport to marker — %d m  (single use, then removed)",
	"İstasyon kiti yok — üsten al": "No station kit — buy one at the base",
	"Buraya istasyon kur (%d m)": "Build a station here (%d m)",
	"Buraya kurulamaz — en az %d m, istasyonlar %d m aralıklı": "Can't build here — at least %d m deep, stations %d m apart",
	# --- sabit tablolar (Ayarlar) ---
	"Toprak": "Soil",
	"Taş": "Stone",
	"Sert Taş": "Hard Stone",
	"Bazalt": "Basalt",
	"Çekirdek Kabuğu": "Core Crust",
	"Bakır": "Copper",
	"Demir": "Iron",
	"Altın": "Gold",
	"Elmas": "Diamond",
	"Platin": "Platinum",
	"Matkap": "Drill",
	"Yakıt deposu": "Fuel tank",
	"Yük kasası": "Cargo bay",
	"Gövde zırhı": "Hull armor",
	"Maden radarı": "Ore radar",
	"Isı kalkanı": "Heat shield",
	"…  ??? — yeraltındaki gizli odalarda": "…  ??? — in hidden rooms underground",
	"Kırık Pusula": "Broken Compass",
	"Matkap hızı +%5": "Drill speed +5%",
	"İbresi aşağıyı gösteriyor ve hiç şaşmıyor. Kasabanın kurucuları bu pusulayı bir kuyunun dibinde bulmuş; \"aşağıda bizi çeken bir şey var\" demişler ve kazmaya başlamışlar.": "Its needle points down and never wavers. The town's founders found this compass at the bottom of a well; they said \"something down there is pulling us\" and started digging.",
	"Bakır Madalyon": "Copper Medallion",
	"Maden değeri +%4": "Ore value +4%",
	"Arkasında bir sayı kazılı: 250. Madalyonu takanlar bir ölçü ekibiydi. Ölçtükleri şey derinlik değil, sıcaklığın nereden geldiğiydi — ve cevap yukarıdan değildi.": "A number is carved on the back: 250. Whoever wore it was a survey crew. What they measured wasn't depth but where the heat came from — and the answer wasn't above.",
	"Kadim Depo Kapağı": "Ancient Tank Lid",
	"Yakıt kapasitesi +%8": "Fuel capacity +8%",
	"Kapağın iç yüzünde bir liste var: inen ekiplerin adları. Son satır yarım kalmış. Deponun kendisi hiç bulunamadı; yakıtı aşağıdan çıkarıyorlardı, yukarıdan indirmiyorlardı.": "The inside of the lid holds a list: the names of the crews who went down. The last line is unfinished. The tank itself was never found; they drew fuel from below instead of lowering it from above.",
	"Taş Tablet": "Stone Tablet",
	"Yük kapasitesi +2": "Load capacity +2",
	"Tablette tek bir cümle var: \"Kabuk her beş nöbette bir kımıldar, tünelleri geri alır.\" Depremleri bir felaket değil, nefes alma sayıyorlardı.": "The tablet has one sentence: \"The crust stirs every fifth watch and takes the tunnels back.\" They counted the quakes not as a disaster but as breathing.",
	"Isıyutan Levha": "Heat-Eater Plate",
	"Çekme ücreti -%20": "Tow fee -20%",
	"Lavın içinde soğuk duruyor. Bu levhayı yapan atölye 210 metrenin altındaydı — yani çekirdeğin kabuğunda. Birileri oraya kadar inmiş, yerleşmiş ve çalışmış.": "It stays cold inside the lava. The workshop that made this plate was below 210 meters — in the core's crust itself. Someone went all the way down, settled, and worked there.",
	"Çekirdek Parçası": "Core Fragment",
	"Matkap hızı +%8": "Drill speed +8%",
	"Elde tutulunca kendi ritmiyle atıyor. Çekirdek bir maden yatağı değil: canlı, yavaş ve sabırlı bir şey. Aşağı inen ekipler onu çıkarmaya değil, uyandırmaya gitmişti.": "Held in the hand, it beats to its own rhythm. The core isn't an ore deposit: it's something alive, slow and patient. The crews who went down didn't go to extract it, but to wake it.",
	"Uyanmış Kabuk Parçası": "Awakened Crust Fragment",
	"Işık yarıçapı +1": "Light radius +1",
	"Yüzeyde soğuk, elde sıcak. Çekirdeğe bir kez dokunulunca uyudu sanmıştık; uyanmıştı. Kabuk artık beş nöbette değil dörtte bir kımıldıyor ve karanlık daha yakından bakıyor. Bu parça kendi ışığını taşıyor — aşağı inen ekiplerin yolu bulmak için değil, geri dönebilmek için aradığı şey buydu.": "Cold at the surface, warm in the hand. When the core was touched once, we thought it went back to sleep; it had woken. The crust now stirs every fourth watch, not the fifth, and the dark looks closer. This fragment carries its own light — what the crews sought wasn't a way down, but a way back.",
}
